version: '3.2'
services:

  turizem-database:
    image: turizem-database
    build: ./Database
    container_name: turizem-database
    restart: unless-stopped
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    env_file:
      - ./turizem.env
    ports:
      - "5432:5432"
    networks:
      - turizem
      
  turizem-keycloak:
    image: turizem-keycloak
    build: ./Keycloak
    container_name: turizem-keycloak
    restart: unless-stopped
    volumes:
      - keycloak_db:/turizem-keycloak/keycloak-5.0.0/standalone/data
    env_file:
      - ./turizem.env
    ports:
      - "8080:8080"
    networks:
      - turizem   

  turizem-backend:
    image: turizem-backend
    depends_on:
      - turizem-database
      - turizem-keycloak
    build:
      context: ./Backend
    container_name: turizem-backend
    restart: unless-stopped
    env_file:
      - ./turizem.env
    ports:
      - "3000:3000"
    networks:
      - turizem

networks:
  turizem:
    driver: bridge

volumes:
  keycloak_db: 
  postgresql_data:     
  
  

