kumuluzee:
  cors-filter:
    servlet:
      allow-origin: "*"
      supported-methods: "GET,HEAD,POST,PUT,DELETE,OPTIONS"
      supported-headers: "Authorization,Origin,Accept,Content-Type,Access-Control-Allow-Origin,Access-Control-Request-Headers"
      exposed-headers: "X-Total-Count"
      supports-credentials: true
      max-age: 3600
  datasources:
    - jndi-name: jdbc/turizem
      connection-url: jdbc:postgresql://localhost:5432/turizem
      username: postgres
      password: ---
      pool:
        max-size: 20